[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
gas_reports = ["FlashFundStakeManager", "FlashFundWithdrawalManager"]
