[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[dependencies]
forge-std = "1.9.3"
solady = { version = "0.0.259", git = "https://github.com/Vectorized/solady.git", rev = "7deab021af0426307ae79d091c4d1e26e9e89cf0" }
openzeppelin = { version = "5.0.2", git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", rev = "bc1df46eac3b897bc343952fccac3fad8a3095bc" }
